import { Video } from '../types';

/**
 * Videos mock de YouTube para demostración
 * Estos videos se combinan con los videos reales del usuario en la galería
 * NOTA: Videos seleccionados que DEFINITIVAMENTE permiten embedding
 * Usamos videos de canales oficiales que siempre permiten embedding
 */
export const MOCK_YOUTUBE_VIDEOS: Video[] = [
  {
    id: 'mock-youtube-1',
    title: 'Big Buck Bunny - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/YE7VzlLtp-4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=YE7VzlLtp-4',
    authorId: 'mock-author-1',
    authorName: 'Alex Rodriguez',
    categories: ['Mejor Videoclip', 'Mejor Dirección', 'Mejor Fotografía'],
    votes: 342,
    views: 125000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-2',
    title: 'Sintel - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/eRsGyueVLvQ/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=eRsGyueVLvQ',
    authorId: 'mock-author-2',
    authorName: 'Sofia Martinez',
    categories: ['Mejor Videoclip', 'Mejor Arte', 'Mejor Color'],
    votes: 289,
    views: 98000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-3',
    title: 'Tears of Steel - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/_c2JYf6wYcI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=_c2JYf6wYcI',
    authorId: 'mock-author-3',
    authorName: 'Carlos Fernandez',
    categories: ['Mejor Fotografía', 'Mejor Montaje'],
    votes: 256,
    views: 87000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-4',
    title: 'Elephants Dream - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/_c2JYf6wYcI/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=_c2JYf6wYcI',
    authorId: 'mock-author-4',
    authorName: 'Laura Garcia',
    categories: ['Mejor Dirección', 'Mejor Arte', 'Mejor Color'],
    votes: 421,
    views: 156000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-5',
    title: 'Spring - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/WhWc3b3KhnY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=WhWc3b3KhnY',
    authorId: 'mock-author-5',
    authorName: 'Miguel Torres',
    categories: ['Mejor Videoclip', 'Mejor Montaje', 'Mejor Fotografía'],
    votes: 378,
    views: 134000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-6',
    title: 'Agent 327 - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/6duu8VxwjqY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=6duu8VxwjqY',
    authorId: 'mock-author-6',
    authorName: 'Ana Lopez',
    categories: ['Mejor Dirección', 'Mejor Arte'],
    votes: 312,
    views: 112000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-7',
    title: 'Hero - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/9IYRC7g2ICg/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=9IYRC7g2ICg',
    authorId: 'mock-author-7',
    authorName: 'David Ruiz',
    categories: ['Mejor Videoclip', 'Mejor Color', 'Mejor Fotografía'],
    votes: 445,
    views: 178000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-8',
    title: 'Glass Half - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/8mBJD7X3j40/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=8mBJD7X3j40',
    authorId: 'mock-author-8',
    authorName: 'Elena Vazquez',
    categories: ['Mejor Arte', 'Mejor Montaje', 'Mejor Color'],
    votes: 267,
    views: 95000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-9',
    title: 'Cosmos Laundromat - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/y7LAbdo82Gs/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=y7LAbdo82Gs',
    authorId: 'mock-author-9',
    authorName: 'Roberto Sanchez',
    categories: ['Mejor Videoclip', 'Mejor Dirección', 'Mejor Arte'],
    votes: 523,
    views: 210000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-10',
    title: 'Caminandes - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/Z4C82eyfw0g/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=Z4C82eyfw0g',
    authorId: 'mock-author-10',
    authorName: 'Carmen Morales',
    categories: ['Mejor Fotografía', 'Mejor Color', 'Mejor Montaje'],
    votes: 389,
    views: 145000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-11',
    title: 'Agent 327: Operation Barbershop - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/6duu8VxwjqY/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=6duu8VxwjqY',
    authorId: 'mock-author-11',
    authorName: 'Javier Moreno',
    categories: ['Mejor Videoclip', 'Mejor Dirección'],
    votes: 234,
    views: 78000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
  {
    id: 'mock-youtube-12',
    title: 'Big Buck Bunny Trailer - Blender Foundation',
    thumbnail: 'https://i.ytimg.com/vi/YE7VzlLtp-4/hqdefault.jpg',
    videoUrl: 'https://www.youtube.com/watch?v=YE7VzlLtp-4',
    authorId: 'mock-author-12',
    authorName: 'Patricia Jimenez',
    categories: ['Mejor Arte', 'Mejor Color', 'Mejor Fotografía'],
    votes: 456,
    views: 167000,
    materialsUsed: 'Blender, Open Source Animation',
    description: 'Video de demostración que definitivamente permite embedding.',
    round: 1,
    year: 2024,
  },
];
